// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

const connectionUrl = process.env["DIRECT_URL"] ?? process.env["DATABASE_URL"];

if (!connectionUrl) {
  throw new Error("DIRECT_URL o DATABASE_URL debe estar configurada.");
}

const sslConnectionUrl = connectionUrl.includes("sslmode=")
  ? connectionUrl
  : `${connectionUrl}${connectionUrl.includes("?") ? "&" : "?"}sslmode=require`;

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: sslConnectionUrl,
  },
});
